package de.agentbase.gema.match;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18.redhat-1
 * 2016-08-04T20:32:17.820+02:00
 * Generated source version: 2.7.18.redhat-1
 * 
 */
@WebServiceClient(name = "MatchingService", 
                  wsdlLocation = "http://localhost:8000/Matching?WSDL",
                  targetNamespace = "http://it4ipm.de/") 
public class MatchingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://it4ipm.de/", "MatchingService");
    public final static QName MatchingPort = new QName("http://it4ipm.de/", "MatchingPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8000/Matching?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MatchingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8000/Matching?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public MatchingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MatchingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MatchingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MatchingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MatchingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MatchingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Matching
     */
    @WebEndpoint(name = "MatchingPort")
    public Matching getMatchingPort() {
        return super.getPort(MatchingPort, Matching.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Matching
     */
    @WebEndpoint(name = "MatchingPort")
    public Matching getMatchingPort(WebServiceFeature... features) {
        return super.getPort(MatchingPort, Matching.class, features);
    }

}
