package de.agentbase.projects.gema_mplus;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(82b97aaa49c8a26cb405ac831f2dd21a)
 */
@org.kie.api.definition.type.Label("MatchCollection")
public class matchCollection extends java.lang.Object implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private match matchToAdd;
   private java.lang.String name;

   private java.util.List<de.agentbase.projects.gema_mplus.match> list;

   public matchCollection()
   {
   }

   public matchCollection(String name)
   {
      list = new ArrayList<de.agentbase.projects.gema_mplus.match>();
      this.name = name;
   }

   public match getMatchToAdd()
   {
      return matchToAdd;
   }

   public void setMatchToAdd(match matchToAdd)
   {
      list.add(matchToAdd);
      this.matchToAdd = matchToAdd;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.List<de.agentbase.projects.gema_mplus.match> getList()
   {
      return this.list;
   }

   public void setList(java.util.List<de.agentbase.projects.gema_mplus.match> list)
   {
      this.list = list;
   }

   public matchCollection(de.agentbase.projects.gema_mplus.match matchToAdd,
         java.lang.String name,
         java.util.List<de.agentbase.projects.gema_mplus.match> list)
   {
      this.matchToAdd = matchToAdd;
      this.name = name;
      this.list = list;
   }
}