package de.agentbase.projects.gema_mplus;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(d7584960a954c674b2bd693120825b51)
 */
@org.kie.api.definition.type.Label(value = "Work")
public class work extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Autor")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String author;
    
    @org.kie.api.definition.type.Label(value = "Datum")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date date;
    
    @org.kie.api.definition.type.Label(value = "Dauer (Sekunden)")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer duration;
    
    @org.kie.api.definition.type.Label(value = "Titel")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String title;

    public work() {
    }

    public work(java.lang.String title, java.lang.String author, java.util.Date date, java.lang.Integer duration) {
        this.title = title;
        this.author = author;
        this.date = date;
        this.duration = duration;
    }


    
    public java.lang.String getAuthor() {
        return this.author;
    }

    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    
    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }
    
    public java.lang.Integer getDuration() {
        return this.duration;
    }

    public void setDuration(java.lang.Integer duration) {
        this.duration = duration;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }
}