package de.agentbase.projects.gema_mplus;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(82b97aaa49c8a26cb405ac831f2dd21a)
 */
@org.kie.api.definition.type.Label("MatchCollection")
public class matchCollection extends java.lang.Object implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Match")
   @org.kie.api.definition.type.Position(0)
   private java.util.List<de.agentbase.projects.gema_mplus.match> match;

   private match matchToAdd;
   private boolean stopAdding;

   private java.lang.String name;

   public matchCollection()
   {
      match = new ArrayList<de.agentbase.projects.gema_mplus.match>();
   }

   public java.util.List<de.agentbase.projects.gema_mplus.match> getMatch()
   {
      return this.match;
   }

   public void setMatch(java.util.List<de.agentbase.projects.gema_mplus.match> match)
   {
      this.match = match;
   }

   public match getMatchToAdd()
   {
      return matchToAdd;
   }

   public void setMatchToAdd(match matchToAdd)
   {
      match.add(matchToAdd);
      this.matchToAdd = matchToAdd;
   }

   public boolean isStopAdding()
   {
      return stopAdding;
   }

   public void setStopAdding(boolean stopAdding)
   {
      this.stopAdding = stopAdding;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public matchCollection(
         java.util.List<de.agentbase.projects.gema_mplus.match> match,
         de.agentbase.projects.gema_mplus.match matchToAdd,
         boolean stopAdding, java.lang.String name)
   {
      this.match = match;
      this.matchToAdd = matchToAdd;
      this.stopAdding = stopAdding;
      this.name = name;
   }

   public matchCollection(
         java.util.List<de.agentbase.projects.gema_mplus.match> match)
   {
      this.match = match;
   }
}