package de.agentbase.projects.gema_mplus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class matchResultList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public matchResultList() {
    }

}